version: 2  
jobs:
  build:
    branches:
      only:
        - main
    docker:
     - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check current version of node
          command: node -v
      - run:
           name: Installing the AWS-CLI
           command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awscli
            aws --version
